#!/usr/bin/env python
import itertools
import logging
import random
from subprocess import Popen, PIPE

import dbus
from dbus import service
from dbus.mainloop.glib import DBusGMainLoop
import gobject


BUS_NAME = 'org.freedesktop.Notifications'
SERVICE_PATH = '/org/freedesktop/Notifications'

REASONS = dict(
    EXPIRED=1,
    DISMISSED=2,
    REQUESTED=3,
    UNDEFINED=4)


class NotificationService(service.Object):
    def __init__(self, open_notification, close_notification):
        self._open_notification = open_notification
        self._close_notification = close_notification

        bus_name = service.BusName(BUS_NAME, bus=dbus.SessionBus())
        super(NotificationService, self).__init__(bus_name, SERVICE_PATH)

    @service.method(BUS_NAME, in_signature='', out_signature='ssss')
    def GetServerInformation(self):
        logging.info("GetServerInformation()")
        return ("wmii-notify-daemon", "wmii", "1.0", "1")

    @service.method(BUS_NAME, in_signature='', out_signature='as')
    def GetCapabilities(self):
        logging.info("GetCapabilities()")
        return ('body')

    @service.method(BUS_NAME, in_signature='susssasa{sv}i', out_signature='u')
    def Notify(self, app_name, replaces_id,
               app_icon, summary, body,
               actions, hints, timeout):
        logging.info("Notify({}, {}, {}, {}, {}, {}, {}, {})".format(
            app_name, replaces_id,
            app_icon, summary, body,
            actions, hints, timeout))
        try:
            return self._open_notification(app_name, replaces_id,
                                          app_icon, summary, body,
                                          actions, hints, timeout)
        except:
            logging.exception("error in Notify")
            raise

    @service.method(BUS_NAME, in_signature='u', out_signature='')
    def CloseNotification(self, id):
        logging.info("CloseNotification({})".format(id))
        try:
            self._close_notification(id, "REQUESTED")
        except:
            logging.exception("error in CloseNotification")
            raise

    @service.signal(BUS_NAME, signature='uu')
    def NotificationClosed(self, id_in, reason_in):
        logging.info("NotificationClosed({}, {})".format(id_in, reason_in))

    @service.signal(BUS_NAME, signature='us')
    def ActionInvoked(self, id_in, action_key_in):
        logging.info("ActionInvoked({}, {})".format(id_in, action_key_in))


class NotificationManager(object):
    def __init__(self, priority=100,
                 low_colours=None, normal_colours=None, critical_colours=None):

        # iterator providing unique id's for each new notification
        self._notification_id = itertools.count(1)

        # map from notification id's to gobject timeout callback handles
        self._notification_timeouts = {}

        self._dbus_service = NotificationService(self.open_notification,
                                                 self.close_notification)

        # number used to determine sort order on bar
        self._priority = 100

        # random string to distinguish this notify server from others
        self._uid = random.randrange(16**8 - 1)

        default_colours = (low_colours or
                           normal_colours or
                           critical_colours or
                           "#ffffff #000000 #aaaaaa")
        self.colours = (
            low_colours or default_colours,
            normal_colours or default_colours,
            critical_colours or default_colours)

    def _notification_filename(self, id):
        return "/rbar/{:03}-{:08x}-notify-{:08}".format(self._priority,
                                                        self._uid,
                                                        id)

    def open_notification(self, app_name, id,
                         app_icon, summary, body,
                         actions, hints, timeout):
        if not id:
            id = next(self._notification_id)

        filename = self._notification_filename(id)

        urgency = max(0, min(hints.get('urgency', 1), 2))
        colours = self.colours[urgency]

        p = Popen(["wmiir", "create", filename], stdin=PIPE)
        p.communicate(colours.encode("utf-8"))
        p.wait(3)

        p = Popen(["wmiir", "write", filename], stdin=PIPE)
        p.communicate(summary.encode("utf-8"))
        p.wait(3)

        if timeout > 0:
            self._notification_timeouts[id] = gobject.timeout_add(
                timeout, self.close_notification, id, "EXPIRED")
        return id

    def close_notification(self, id, reason="UNDEFINED"):
        logging.info("closing notification with id: {}, reason: {}".format(
            id, reason))
        if id in self._notification_timeouts:
            del self._notification_timeouts[id]

        # TODO check if filename exists
        filename = self._notification_filename(id)
        p = Popen(["wmiir", "remove", filename])
        p.wait(3)

        self._dbus_service.NotificationClosed(id, REASONS[reason])


def main():
    gobject.threads_init()

    logging.basicConfig(level=logging.DEBUG)

    DBusGMainLoop(set_as_default=True)
    NotificationManager()

    mainloop = gobject.MainLoop()
    mainloop.run()

if __name__ == "__main__":
    main()
